# This module looks for libxml2 (http://www.xmlsoft.org) support
# it will define the following values
#
# LIBXML2_INCLUDE_DIR  = where libxml/xpath.h can be found
# LIBXML2_LIBRARIES    = the libraries to link against libxml2
# LIBXML2_FOUND        = set to 1 if libxml2 is found
#
IF(EXISTS ${PROJECT_CMAKE}/libxml2Config.cmake)
  INCLUDE(${PROJECT_CMAKE}/libxml2Config.cmake)
ENDIF(EXISTS ${PROJECT_CMAKE}/libxml2Config.cmake)

IF(libxml2_INCLUDE_DIRS)

  FIND_PATH(LIBXML2_INCLUDE_DIR libxml/xpath.h ${libxml2_INCLUDE_DIRS})
  FIND_LIBRARY(LIBXML2_LIBRARIES NAMES xml2 :libxml2.a PATHS ${libxml2_LIBRARY_DIRS})

ELSE(libxml2_INCLUDE_DIRS)

  FIND_PATH(LIBXML_INCLUDE_DIR libxml2/libxml/xpath.h ${APP_INCLUDE_PATHS})
  if(LIBXML_INCLUDE_DIR)
    set(LIBXML2_INCLUDE_DIR "${LIBXML_INCLUDE_DIR}/libxml2")
  else(LIBXML_INCLUDE_DIR)
    FIND_PATH(LIBXML2_INCLUDE_DIR libxml/xpath.h ${APP_INCLUDE_PATHS})
  endif(LIBXML_INCLUDE_DIR)

  FIND_LIBRARY(LIBXML2_LIBRARIES NAMES libxml2 PATHS ${APP_LIBRARY_PATHS})

ENDIF(libxml2_INCLUDE_DIRS)

SET(LIBXML2_FOUND FALSE)
IF(LIBXML2_INCLUDE_DIR AND LIBXML2_LIBRARIES)
  message(STATUS "LIBXML2_INCLUDE_DIR="${LIBXML2_INCLUDE_DIR})
  message(STATUS "LIBXML2_LIBRARIES="${LIBXML2_LIBRARIES})
  SET(LIBXML2_FOUND TRUE)
ENDIF()

MARK_AS_ADVANCED(
  LIBXML2_INCLUDE_DIR
  LIBXML2_LIBRARIES
  LIBXML2_FOUND
)

